server:
  port: 9200
spring:
  application:
    name: api-gateway
  jackson:
    default-property-inclusion: non_null
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        filters:
          - name: EndpointFIlter
        routes:
          - id: items-service
            uri: lb://items-service
            predicates:
              - Path=/items/**
            filters:
              - RewritePath=/items/(?<segment>.*), /$\{segment}

service:
  authorization-server: http://localhost:9100/validate

logging:
  level:
    com.salazar.security: DEBUG
    reactor.netty.http.client: ERROR
    org:
      springframework:
        web:
          client: ERROR
        cloud:
          gateway: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  register-with-eureka: true